In [1]:
import numpy as np

In [2]:
t=np.array([[1,2,3],[4,5,6]])
t1=t*2
print("\n",t1)
t2=t+3
print("\n",t2)
t3=np.power(t,2)
print("\n",t3)
t4=np.transpose(t)
print("\n",t4)


 [[ 2  4  6]
 [ 8 10 12]]

 [[4 5 6]
 [7 8 9]]

 [[ 1  4  9]
 [16 25 36]]

 [[1 4]
 [2 5]
 [3 6]]
